apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resource/helm-repository.yaml
  - resource/prometheus-helmrelease.yaml
  - resource/grafana-helmrelease.yaml
  - resource/loki-helmrelease.yaml

namespace: monitoring