# grafana-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: grafana
  targetNamespace: default
  chart:
    spec:
      chart: grafana/grafana
      version: 8.5.0
      sourceRef:
        kind: HelmRepository
        name: grafana
