# loki-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "latest"
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    # Add any Loki specific values here
