# loki-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: loki
  targetNamespace: default
  chart:
    spec:
      chart: grafana/loki
      version: 6.10.1
      sourceRef:
        kind: HelmRepository
        name: grafana
