# prometheus-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "latest"
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    # Add any Prometheus specific values here
