apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  provider: kubernetes-monitoring

resources:
  - resource/helm-repository.yaml
  - resource/prometheus-helmrelease.yaml
  - resource/grafana-helmrelease.yaml
  - resource/loki-helmrelease.yaml