# # grafana-helmrelease.yaml
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: grafana
#   namespace: flux-system
# spec:
#   interval: 5m0s
#   releaseName: grafana
#   targetNamespace: default
#   chart:
#     spec:
#       chart: grafana/grafana
#       version: 8.5.0
#       sourceRef:
#         kind: HelmRepository
#         name: grafana


apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana2
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: grafana
  chart:
    repository: https://grafana.github.io/helm-charts
    name: grafana
    version: 8.5.0
