# prometheus-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: prometheus
  targetNamespace: default
  chart:
    spec:
      chart: prometheus-community/prometheus
      version: 25.27.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
